### ISSUE TITLE
Add stats page

### ISSUE THREAD

**Issue by bcai2** [cardinalitypuzzles/smallboard#311]
In prep for a place to put the progress chart (#200), having a page displaying hunt statistics would be nice.

Things to do:
- [x] Make the page and link it to the frontpage of a hunt (#318)
- [x] Add basic stats (solves, open puzzles, unsolved, meta solves) (#318)
  - [x] Integrate basic stats with main hunt (puzzle) view
- [x] Add time-based stats (solves/hr, mins/solve) (also #318)
- [ ] Make page update periodically (e.g., every 10 seconds like the puzzles page does)

Adding the progress chart should be the ultimate goal.

**Comment by bcai2** [comment]
Marking this as resolved and merging the updating into the update issue (#390).
